- name: Download terraform tar
  get_url:
    url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: "{{ downloads_path }}/terraform_{{ terraform_version }}_linux_amd64.zip"
  tags: terraform

- name: Unpack gzip file
  unarchive:
    src: "{{ downloads_path }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: /usr/local/bin
    copy: no
    owner: root
    group: root
  tags: terraform

# - name: Create symlink to current version
#   file:
#     src: /usr/local/terraform_{{ terraform_version }}_linux_amd64/terraform_{{ terraform_version }}_linux_amd64
#     dest: /usr/local/bin/terraform
#     owner: root
#     group: root
#     state: link
#   tags: terraform
