---
- name: Copy logsec icon
  ansible.builtin.copy:
    src: logsec-icon.png
    dest: /opt/gnome-desktop-entries/logsec-icon.png
    owner: root
    group: root
    mode: "0644"

- name: Create desktop entry for logseq
  ansible.builtin.copy:
    content: |
      [Desktop Entry]
      Encoding=UTF-8
      Name=LogSeq
      Comment=Take notes
      Exec=/usr/local/bin/logseq
      Icon=/opt/gnome-desktop-entries/logseq-icon.png
      Terminal=false
      Type=Application
      StartupNotify=true
      Categories=GNOME;Utility
    dest: /usr/share/applications/logseq.desktop
    owner: root
    group: root
    mode: "0644"
