---

- name: Copy obsidian icon
  ansible.builtin.copy:
    src: obsidian-icon.svg
    dest: /opt/gnome-desktop-entries/obsidian-icon.svg
    owner: root
    group: root
    mode: '0644'

- name: Create desktop entry for obsidian
  ansible.builtin.copy:
    content: |
      [Desktop Entry]
      Encoding=UTF-8
      Name=Obsidian
      Comment=Notes/PKM
      Exec=/usr/local/bin/obsidian
      Icon=/opt/gnome-desktop-entries/obsidian-icon.svg
      Terminal=false
      Type=Application
      StartupNotify=true
      Categories=GNOME;Utility
    dest: /usr/share/applications/obsidian.desktop
    owner: root
    group: root
    mode: '0644'
