---
- name: Create desktop entry for wave
  ansible.builtin.copy:
    content: |
      [Desktop Entry]
      Type=Application
      Encoding=UTF-8
      Name=Wave Terminal
      Comment=Terminal
      Exec=/home/nelly/.local/bin/wave
      Icon=/home/nelly/.local/Wave-linux-x64/resources/app/public/waveterm.icns
      # setting this to true will launch an extra terminal to run the Wave command
      Terminal=false
    dest: /usr/share/applications/wave.desktop
    owner: root
    group: root
    mode: "0644"
