# pub keys
keys:
  users:
    - &nelly age1t9wdp4gya7hqkh3ge08nqsh0jhsfvu52d0qhqvdvrgsxe7c0eeeqnc5ta5
  hosts:
    - &ruca age1znnu0vzuz75xgzw5kr74zrvqy9yeqcatcwkzmxvmcy9hvhas396q4mtcn9
    - &lappy age1xfhncyzagtkash7uhw2sl9p907hr30fccrs0ugx6kpum9ry8td5q2gemny

creation_rules:
  - path_regex: secrets/[^/]+\-enc.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *nelly
        - *ruca
        - *lappy
