version: "3"

vars:
  IS_NIXOS:
    sh: if [ -e /etc/NIXOS ]; then echo "true"; else echo "false"; fi
  NIX_CMD:
    sh: if [ -e /etc/NIXOS ]; then echo "sudo nixos-rebuild"; else echo "home-manager"; fi
  NIX_BUILD_CMD:
    sh: if [ -e /etc/NIXOS ]; then echo "nixos-rebuild"; else echo "home-manager"; fi
  DO_IMAGE_NAME: nixos-26.05-v1

tasks:
  echo:
    requires:
      vars:
        - "IS_NIXOS"
        - "NIX_CMD"
    preconditions:
      - '[ {{.IS_NIXOS}} -eq "true" ]'
    cmds:
      - echo {{.NIX_CMD}}

  ### Build

  # build:
  #   internal: true
  #   desc: Build the flake.
  #   requires:
  #     vars:
  #       - "NIX_BUILD_CMD"
  #       - "MACHINE"
  #   cmds:
  #     - "{{.NIX_BUILD_CMD}} build --flake .#{{.MACHINE}}" # --print-build-logs --verbose

  build-machine:
    desc: Build a machine configuration
    internal: true
    requires:
      vars:
        - name: MACHINE
          enum: [ruca, lappy]
    cmds:
      - nix build .#nixosConfigurations.{{.MACHINE}}.config.system.build.toplevel --out-link result-{{.MACHINE}} # use this instead of nixos-rebuild to control the result directory

  build-ruca:
    desc: Build the ruca configuration
    cmds:
      - task: build-machine
        vars: { MACHINE: ruca }
      - task: niri-validate
        vars: { RESULT: "result-ruca" }

  build-lappy:
    desc: Build the lappy configuration
    cmds:
      - task: build-machine
        vars: { MACHINE: lappy }

  build-do-image:
    desc: Build the Digital Ocean custom image
    cmd: nix build .#do-image --print-out-paths --out-link result-do-image

  build-iso:
    internal: true
    desc: Build an installer ISO [gnome|min]
    requires:
      vars:
        - name: ISO
          enum: [min, gnome]
    cmd: nix build .#nixosConfigurations.iso-{{.ISO}}.config.system.build.isoImage --print-out-paths --out-link result-iso-{{.ISO}}

  build-iso-min:
    desc: Build the minimal installer ISO
    cmds:
      - task: build-iso
        vars: { ISO: "min" }

  build-iso-gnome:
    desc: Build the gnome installer ISO
    cmds:
      - task: build-iso
        vars: { ISO: "gnome" }

  build-hives:
    desc: Build all hives without deploying
    cmd: nix run .#colmena -- build --impure

  build-hive-internal:
    desc: Build a hive without deploying
    internal: true
    requires:
      vars:
        - name: HIVE
          enum: [local, do, dns, cbox, illmatic, nixos-test-01]
    cmd: nix run .#colmena -- build --impure --on @{{.HIVE}}

  build-hive:
    desc: Build a hive without deploying
    cmds:
      - task: build-hive-internal
        vars: { HIVE: "{{.CLI_ARGS}}" }

  build-hive-do:
    desc: Build digital ocean hive without deploying
    cmds:
      - task: build-hive-internal
        vars: { HIVE: do }

  build-hive-local:
    desc: Build digital ocean hive without deploying
    cmds:
      - task: build-hive-internal
        vars: { HIVE: local }

  build-machines:
    deps: [build-ruca, build-lappy]

  build-images:
    deps: [build-do-image, build-iso-min, build-iso-gnome]

  build-all:
    desc: Build everything.
    cmds:
      - task: build-machines
      - task: build-hives
      - task: build-images

  build-all-seq:
    desc: Build everything sequentially.
    cmds:
      - task: build-ruca
      - task: build-lappy
      - task: build-hives
      - task: build-do-image
      - task: build-iso-min
      - task: build-iso-gnome

  niri-validate:
    internal: true
    desc: Validate the Niri configuration KDL files in a build.
    vars:
      RESULT: '{{default "result" .RESULT}}'
    cmds:
      - |
        HM_FILES="$(nix-store -q --tree {{.RESULT}} | rg -o -m 1 '/nix/store/[a-z0-9]+-home-manager-files')"
        test -n "$HM_FILES"
        test -f "$HM_FILES/.config/niri/config.kdl"
        niri validate -c "$HM_FILES/.config/niri/config.kdl"

  switch:
    desc: Build then switch to the new build.
    cmd: "{{.NIX_CMD}} switch --flake ."

  boot:
    desc: Build a flake and set for next boot.
    internal: true
    requires:
      vars:
        - name: MACHINE
          enum: [ruca, lappy]
    cmds:
      - "sudo nixos-rebuild boot --flake .#{{.MACHINE}}"

  boot-ruca:
    desc: Build the flake and set for next boot.
    deps: [build-ruca]
    cmds:
      - task: boot
        vars: { MACHINE: ruca }

  deploy:
    desc: Deploy configuration to remote host
    cmds:
      - nixos-rebuild switch --flake .#{{.CLI_ARGS}} --target-host sysconf@{{.CLI_ARGS}} --sudo --ask-sudo-password

  clean:
    desc: Delete the result directories that the build task creates.
    cmds:
      - rm -rf result
      - rm -rf result-*

  update:
    desc: Update packages and the lock file.
    cmds:
      - nix flake update {{.CLI_ARGS}}

  update-secrets:
    desc: Update the secrets
    cmds:
      - nix flake update sysconf-secrets

  upload-do-image:
    desc: Upload the do-image
    deps: [build-do-image]
    cmds:
      - |
        set -- ./result-do-image/*.qcow2.gz
        test -f "$1"
        test "$#" -eq 1
        s3cmd -c ~/secret/sysconf/digital-ocean/s3-images-creds \
        put "$1" \
        s3://sysconf-images/{{.DO_IMAGE_NAME}}.qcow2.gz \
        --acl-public

  ### Garbage collection
  gc:
    desc: Run both gc tasks.
    deps: [gc-os, gc-hm]

  gc-hm:
    desc: Delete old unused home manager packages.
    cmds:
      - nix-collect-garbage --delete-older-than 14d # home-manager stuff in user's home directory

  gc-os:
    desc: Delete old unused system packages.
    requires:
      vars:
        - "IS_NIXOS"
    preconditions:
      - '[ {{.IS_NIXOS}} -eq "true" ]'
    cmds:
      - sudo nix-collect-garbage --delete-older-than 14d # system wide

  ### ISO
  iso-burn:
    desc: Burn an iso to a USB drive
    internal: true
    requires:
      vars:
        - name: ISO
          enum: [min, gnome]
    cmd: caligula burn $(gum file ./result-iso-{{.ISO}}/iso)

  iso-burn-min:
    desc: Burn the minimal ISO to disk
    cmds:
      - task: iso-burn
        vars: { ISO: "min" }

  iso-burn-gnome:
    desc: Burn the gnome ISO to disk
    cmds:
      - task: iso-burn
        vars: { ISO: "gnome" }

  iso-copy:
    desc: Copy a iso to a USB drive
    internal: true
    requires:
      vars:
        - name: ISO
          enum: [min, gnome]
    cmd: cp result-iso-{{.ISO}}/iso/*.iso /run/media/$USER/Ventoy

  iso-copy-min:
    desc: Copy the minimal ISO to a USB drive
    cmds:
      - task: iso-copy
        vars: { ISO: "min" }

  iso-copy-gnome:
    desc: Copy the GNOME ISO to a USB drive
    cmds:
      - task: iso-copy
        vars: { ISO: "gnome" }

  #### Colmena
  deploy-hive-internal:
    desc: Deploy a hive
    internal: true
    requires:
      vars:
        - name: HIVE
          enum: [local, do, dns, cbox, illmatic, nixos-test-01]
    cmd: nix run .#colmena -- apply --impure --on @{{.HIVE}}

  deploy-hive:
    desc: Deploy a hive
    cmds:
      - task: deploy-hive-internal
        vars: { HIVE: "{{.CLI_ARGS}}" }

  deploy-hive-do:
    desc: Deploy the digital ocean hive
    cmds:
      - task: deploy-hive-internal
        vars: { HIVE: do }

  deploy-hive-local:
    desc: Deploy the local hive
    cmds:
      - task: deploy-hive-internal
        vars: { HIVE: local }

  deploy-hives:
    desc: Deploy all hives
    cmd: nix run .#colmena -- apply --impure

  upload-keys:
    desc: Upload deploy keys to a hive. Required after reboot.
    cmds:
      - nix run .#colmena -- upload-keys --impure --on @{{.CLI_ARGS}}
      # Update password after key upload (hashedPasswordFile requires activation to update /etc/shadow)
      - ssh sysconf@{{.CLI_ARGS}} "sudo /run/current-system/activate"

  ### Tests
  test-blocky:
    desc: Test Blocky DNS servers
    cmds:
      - ./nix/modules/system/services/blocky/test.sh 10.42.10.22
      - ./nix/modules/system/services/blocky/test.sh 10.42.10.23

  ## Utils
  news:
    desc: Display Home Manager news
    cmds:
      - home-manager news --flake .

  history:
    desc: List all previous generations available.
    cmd: nix profile history --profile /nix/var/nix/profiles/system

  eval:
    desc: Show a configuration value.
    cmds:
      - nix eval .#{{.CLI_ARGS}} # task eval -- nixosConfigurations.ruca.config.services.xserver.videoDrivers

  option:
    desc: Show the calculated value of a flake option.
    cmds:
      - nixos-option --flake . {{.CLI_ARGS}}
