version: "3"

vars:
  IS_NIXOS:
    sh: if [ -e /etc/NIXOS ]; then echo "true"; else echo "false"; fi
  NIX_CMD:
    sh: if [ -e /etc/NIXOS ]; then echo "sudo nixos-rebuild"; else echo "home-manager"; fi
  NIX_BUILD_CMD:
    sh: if [ -e /etc/NIXOS ]; then echo "nixos-rebuild"; else echo "home-manager"; fi

tasks:
  echo:
    requires:
      vars:
        - "IS_NIXOS"
        - "NIX_CMD"
    preconditions:
      - '[ {{.IS_NIXOS}} -eq "true" ]'
    cmds:
      - echo {{.NIX_CMD}}

  # build:
  #   internal: true
  #   desc: Build the flake.
  #   requires:
  #     vars:
  #       - "NIX_BUILD_CMD"
  #       - "MACHINE"
  #   cmds:
  #     - "{{.NIX_BUILD_CMD}} build --flake .#{{.MACHINE}}" # --print-build-logs --verbose

  build-ruca:
    desc: Build the ruca configuration
    cmds:
      - nix build .#nixosConfigurations.ruca.config.system.build.toplevel --out-link result-ruca
      - task: niri-validate
        vars: { RESULT: result-ruca }

  # build-ruca:
  #   desc: Build the ruca configuration
  #   cmds:
  #     - nixos-rebuild build --flake .#ruca
  #     - task: niri-validate

  build-lappy:
    desc: Build the lappy configuration
    cmd: nixos-rebuild build --flake .#lappy

  build-do-image:
    desc: Build the Digital Ocean custom image
    cmd: nix build .#do-image --print-out-paths

  build-iso:
    internal: true
    desc: Build an installer ISO [gnome|min]
    vars:
      IMAGE: '{{default "min" .IMAGE}}'
    cmd: nix build .#nixosConfigurations.iso-{{.IMAGE}}.config.system.build.isoImage --print-out-paths

  build-iso-min:
    desc: Build the min installer ISO
    cmds:
      - task: build-iso
        vars: { IMAGE: "min" }

  build-iso-gnome:
    desc: Build the gnome installer ISO
    cmds:
      - task: build-iso
        vars: { IMAGE: "gnome" }

  build-hives:
    desc: Build all hives without deploying
    cmd: nix run .#colmena -- build --impure

  build-hive:
    desc: Build local hive without deploying
    cmd: nix run .#colmena -- build --impure --on @{{.CLI_ARGS}}

  build-machines:
    internal: true
    deps: [build-ruca, build-lappy]

  build-images:
    internal: true
    deps: [build-do-image, build-iso-min, build-iso-gnome]

  build-all:
    desc: Build everything.
    cmds:
      - task: build-machines
      - task: build-hives
      - task: build-images

  build-all-seq:
    desc: Build everything sequentially.
    cmds:
      - task: build-ruca
      - task: build-lappy
      - task: build-hives
      - task: build-do-image
      - task: build-iso-min
      - task: build-iso-gnome

  switch:
    desc: Build then switch to the new build.
    cmd: "{{.NIX_CMD}} switch --flake ."

  boot:
    desc: Build the flake and set for next boot.
    requires:
      vars:
        - "NIX_CMD"
    cmds:
      - "{{.NIX_CMD}} boot --flake .{{.CLI_ARGS}}"

  deploy:
    desc: Deploy configuration to remote host
    cmds:
      - nixos-rebuild switch --flake .#{{.CLI_ARGS}} --target-host sysconf@{{.CLI_ARGS}} --sudo --ask-sudo-password

  eval:
    desc: Show a configuration value.
    cmds:
      - nix eval .#{{.CLI_ARGS}} # task eval -- nixosConfigurations.ruca.config.services.xserver.videoDrivers

  option:
    desc: Show the calculated value of a flake option.
    cmds:
      - nixos-option --flake . {{.CLI_ARGS}}

  clean:
    desc: Delete the result directory that the build task creates.
    cmds:
      - rm -rf result
      - rm -rf result-ruca

  update:
    desc: Update packages and the lock file.
    cmds:
      - nix flake update {{.CLI_ARGS}}

  gc:
    desc: Run both gc tasks.
    deps: [gc-os, gc-hm]

  gc-hm:
    desc: Delete old unused home manager packages.
    cmds:
      - nix-collect-garbage --delete-older-than 14d # home-manager stuff in user's home directory

  gc-os:
    desc: Delete old unused system packages.
    requires:
      vars:
        - "IS_NIXOS"
    preconditions:
      - '[ {{.IS_NIXOS}} -eq "true" ]'
    cmds:
      - sudo nix-collect-garbage --delete-older-than 14d # system wide

  news:
    desc: Display Home Manager news
    cmds:
      - home-manager news --flake .

  history:
    desc: List all previous generations available.
    cmd: nix profile history --profile /nix/var/nix/profiles/system

  iso-burn:
    desc: Burn an iso to a USB drive
    cmd: caligula burn $(gum file ./result/iso)

  iso-copy:
    desc: Copy the iso to a USB drive
    cmd: cp result/iso/*.iso /run/media/$USER/Ventoy

  deploy-hive:
    desc: Deploy a hive
    cmd: nix run .#colmena -- apply --impure --on @{{.CLI_ARGS}}

  deploy-hives:
    desc: Deploy all hives
    cmd: nix run .#colmena -- apply --impure

  upload-keys:
    desc: Upload deploy keys to a hive. Required after reboot.
    cmds:
      - nix run .#colmena -- upload-keys --impure --on @{{.CLI_ARGS}}
      # Update password after key upload (hashedPasswordFile requires activation to update /etc/shadow)
      - ssh sysconf@{{.CLI_ARGS}} "sudo /run/current-system/activate"

  niri-validate:
    internal: true
    desc: Validate the Niri configuration KDL files in a build.
    vars:
      RESULT: '{{default "result" .RESULT}}'
    cmds:
      - |
        HM_FILES="$(nix-store -q --tree {{.RESULT}} | rg -o -m 1 '/nix/store/[a-z0-9]+-home-manager-files')"
        test -n "$HM_FILES"
        test -f "$HM_FILES/.config/niri/config.kdl"
        niri validate -c "$HM_FILES/.config/niri/config.kdl"

  # niri-validate:
  #   internal: true
  #   desc: Validate the Niri configuration KDL files in a build.
  #   # cmd: find nix/modules/home/desktop -name '*.kdl' -type f -print -exec niri validate -c {} \;
  #   env:
  #     HM_FILES:
  #       sh: nix-store -q --tree result | rg -o -m 1 '/nix/store/[a-z0-9]+-home-manager-files' | head -1
  #   cmd: niri validate -c "$HM_FILES/.config/niri/config.kdl"

  test-blocky:
    desc: Test Blocky DNS servers
    cmds:
      - ./nix/modules/system/services/blocky/test.sh 10.42.10.22
      - ./nix/modules/system/services/blocky/test.sh 10.42.10.23
