version: "3"

# NIX_CMD and IS_NIXOS are set in the devShell of flake.nix
vars:
  IS_NIXOS:
    sh: if [ -e /etc/NIXOS ]; then echo "true"; else echo "false"; fi
  NIX_CMD:
    sh: if [ -e /etc/NIXOS ]; then echo "sudo nixos-rebuild"; else echo "home-manager"; fi

tasks:
  echo:
    requires:
      vars:
        - "IS_NIXOS"
        - "NIX_CMD"
    preconditions:
      - '[ {{.IS_NIXOS}} -eq "true" ]'
    cmds:
      - echo {{.NIX_CMD}}

  build:
    desc: Build the flake.
    requires:
      vars:
        - "NIX_CMD"
    cmds:
      - "{{.NIX_CMD}} build --flake ."

  switch:
    desc: Build then switch to the new build.
    cmds:
      - "{{.NIX_CMD}} switch --flake ."
      - task: dotfiles

  clean:
    desc: Delete the result directory that the build task creates.
    cmds:
      - rm -rf result

  update:
    desc: Update packages and the lock file.
    cmds:
      - nix flake update

  gc:
    desc: Run both gc tasks.
    deps: [gc-os, gc-hm]

  gc-hm:
    desc: Delete old unused home manager packages.
    cmds:
      - nix-collect-garbage --delete-older-than 7d # home-manager stuff in user's home directory

  gc-os:
    desc: Delete old unused system packages.
    requires:
      vars:
        - "IS_NIXOS"
    preconditions:
      - '[ {{.IS_NIXOS}} -eq "true" ]'
    cmds:
      - sudo nix-collect-garbage --delete-older-than 7d # system wide

  news:
    desc: Display Home Manager news
    cmds:
      - home-manager news --flake .

  dotfiles:
    desc: Stow the dotfiles.
    cmds:
      - stow --verbose --stow --dotfiles --target=$HOME --dir=$HOME/sysconf/dotfiles code
      - stow --verbose --stow --dotfiles --target=$HOME --dir=$HOME/sysconf/dotfiles common
      - stow --verbose --stow --dotfiles --target=$HOME --dir=$HOME/sysconf/dotfiles desktop
      - stow --verbose --stow --dotfiles --target=$HOME --dir=$HOME/sysconf/dotfiles wezterm
      # - stow --verbose --stow --dotfiles --target=$HOME --dir=$HOME/sysconf/dotfiles zellij

  clean-dotfiles:
    desc: Unstow the dotfiles.
    cmds:
      - stow --verbose --delete --target=$HOME --dir=$HOME/sysconf/dotfiles code
      - stow --verbose --delete --target=$HOME --dir=$HOME/sysconf/dotfiles common
      - stow --verbose --delete --target=$HOME --dir=$HOME/sysconf/dotfiles desktop
      - stow --verbose --delete --target=$HOME --dir=$HOME/sysconf/dotfiles wezterm
      # - stow --verbose --delete --target=$HOME --dir=$HOME/sysconf/dotfiles zellij

  history:
    desc: List all previous generations available.
    cmd: nix profile history --profile /nix/var/nix/profiles/system

  iso:
    desc: Build an installer ISO
    cmd: nix build .#nixosConfigurations.iso.config.system.build.isoImage

  iso-burn:
    desc: Burn an iso to a USB drive
    cmd: caligula burn $(gum file result/iso)

  iso-copy:
    desc: Copy the iso to a USB drive
    cmd: cp result/iso/*.iso /run/media/$USER/Ventoy
