{
  config,
  lib,
  pkgs,
  pkgs-unstable,
  ...
}:
let
  cfg = config.sysconf.desktop.niri;

  noctaliaSettings = {
    settingsVersion = 0;

    general = {
      telemetryEnabled = false;
      showChangelogOnStartup = true;
    };

    colorSchemes = {
      useWallpaperColors = true;
      predefinedScheme = "Noctalia (default)";
      darkMode = true;
    };

    # Keep this minimal; copy GUI-generated settings if you want full control.
    bar = {
      position = "top";
      density = "compact";
      floating = true;
      backgroundOpacity = 0.93;
    };

    dock = {
      enabled = true;
      position = "bottom";
      displayMode = "auto_hide";
    };

    wallpaper = {
      enabled = true;
      overviewEnabled = false;
      fillMode = "crop";
      setWallpaperOnAllMonitors = true;
    };
  };

  noctaliaWallpapers = {
    defaultWallpaper = "${config.home.homeDirectory}/background-image";
    wallpapers = { };
  };

  niriConfig = ''
    // Generated by sysconf Home Manager module.

    input {
      keyboard {
        numlock
      }

      touchpad {
        tap
        natural-scroll
      }
    }

    // Allow Noctalia to activate windows / actions reliably.
    debug {
      honor-xdg-activation-with-invalid-serial
    }

    // Noctalia wallpaper layers (stationary wallpaper).
    layer-rule {
      match namespace="^noctalia-wallpaper"
      place-within-backdrop true
    }

    layout {
      gaps 16

      // Make workspaces transparent so the wallpaper backdrop shows.
      background-color "transparent"

      focus-ring {
        width 4
        active-color "#a8aeff"
        inactive-color "#505050"
      }

      // Helps with properly drawing borders/rings with rounded corners.
      prefer-no-csd
    }

    // Rounded corners for a modern look.
    window-rule {
      geometry-corner-radius 20
      clip-to-geometry true
    }

    // Optionally, disable workspace shadows in overview.
    overview {
      workspace-shadow {
        off
      }
    }

    // Firefox PiP as floating by default.
    window-rule {
      match app-id=r#"firefox$"# title="^Picture-in-Picture$"
      open-floating true
    }

    // Start systemd user session targets for other HM services.
    // This makes units that want graphical-session.target work without UWSM.
    spawn-sh-at-startup "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE XDG_SESSION_DESKTOP; systemctl --user start graphical-session.target"

    binds {
      Mod+Return { spawn "footclient"; }

      // Noctalia actions
      Mod+Space { spawn "noctalia-shell" "ipc" "call" "launcher" "toggle"; }
      Mod+P { spawn "noctalia-shell" "ipc" "call" "sessionMenu" "toggle"; }
      Mod+Shift+L { spawn "noctalia-shell" "ipc" "call" "lockScreen" "lock"; }

      // Basics
      Mod+O repeat=false { toggle-overview; }
      Mod+Q repeat=false { close-window; }

      // Focus movement (vim-style)
      Mod+H { focus-column-left; }
      Mod+J { focus-window-down; }
      Mod+K { focus-window-up; }
      Mod+L { focus-column-right; }

      // Volume / media via Noctalia
      XF86AudioRaiseVolume allow-when-locked=true { spawn "noctalia-shell" "ipc" "call" "volume" "increase"; }
      XF86AudioLowerVolume allow-when-locked=true { spawn "noctalia-shell" "ipc" "call" "volume" "decrease"; }
      XF86AudioMute allow-when-locked=true { spawn "noctalia-shell" "ipc" "call" "volume" "muteOutput"; }
      XF86AudioMicMute allow-when-locked=true { spawn "noctalia-shell" "ipc" "call" "volume" "muteInput"; }
      XF86AudioPlay allow-when-locked=true { spawn "playerctl" "play-pause"; }
      XF86AudioPrev allow-when-locked=true { spawn "playerctl" "previous"; }
      XF86AudioNext allow-when-locked=true { spawn "playerctl" "next"; }

      // Brightness via Noctalia (uses brightnessctl / ddcutil internally)
      XF86MonBrightnessUp allow-when-locked=true { spawn "noctalia-shell" "ipc" "call" "brightness" "increase"; }
      XF86MonBrightnessDown allow-when-locked=true { spawn "noctalia-shell" "ipc" "call" "brightness" "decrease"; }

      // Screenshots
      Print { spawn-sh "grim - | swappy -f -"; }
      Mod+Shift+S { spawn-sh "grim -g \"$(slurp)\" - | swappy -f -"; }

      // Clipboard history
      Ctrl+Alt+H { spawn "rofi-cliphist"; }

      Mod+Shift+E { quit; }
    }
  '';
in
{
  options.sysconf.desktop.niri = {
    enable = lib.mkEnableOption "niri";
  };

  config = lib.mkIf cfg.enable {
    home = {
      packages =
        with pkgs;
        [
          niri
          foot
          fuzzel
          grim
          mako
          playerctl
          polkit_gnome
          slurp
          swappy
          swayidle
          wl-clipboard
          xdg-desktop-portal-gtk
          xdg-desktop-portal-wlr
        ]
        ++ [ pkgs-unstable.noctalia-shell ];

      file.".cache/noctalia/wallpapers.json".text = builtins.toJSON noctaliaWallpapers;
    };

    xdg.configFile = {
      "niri/config.kdl".text = niriConfig;
      "noctalia/settings.json".text = builtins.toJSON noctaliaSettings;
    };

    xdg.portal = {
      enable = lib.mkDefault true;
      extraPortals = with pkgs; [
        xdg-desktop-portal-gtk
        xdg-desktop-portal-wlr
      ];
    };

    systemd.user.services = {
      noctalia-shell = {
        Unit = {
          Description = "Noctalia Shell";
          PartOf = [ "graphical-session.target" ];
          After = [ "graphical-session.target" ];
        };
        Service = {
          ExecStart = lib.getExe pkgs-unstable.noctalia-shell;
          Restart = "on-failure";
        };
        Install = {
          WantedBy = [ "graphical-session.target" ];
        };
      };

      mako = {
        Unit = {
          Description = "Mako notifications";
          PartOf = [ "graphical-session.target" ];
          After = [ "graphical-session.target" ];
        };
        Service = {
          ExecStart = lib.getExe pkgs.mako;
          Restart = "on-failure";
        };
        Install = {
          WantedBy = [ "graphical-session.target" ];
        };
      };

      polkit-gnome-authentication-agent = {
        Unit = {
          Description = "Polkit authentication agent";
          PartOf = [ "graphical-session.target" ];
          After = [ "graphical-session.target" ];
        };
        Service = {
          ExecStart = "${pkgs.polkit_gnome}/libexec/polkit-gnome-authentication-agent-1";
          Restart = "on-failure";
        };
        Install = {
          WantedBy = [ "graphical-session.target" ];
        };
      };

      swayidle = {
        Unit = {
          Description = "Idle manager";
          PartOf = [ "graphical-session.target" ];
          After = [ "graphical-session.target" ];
        };
        Service = {
          ExecStart = "${pkgs.swayidle}/bin/swayidle -w timeout 600 'noctalia-shell ipc call lockScreen lock' before-sleep 'noctalia-shell ipc call lockScreen lock'";
          Restart = "on-failure";
        };
        Install = {
          WantedBy = [ "graphical-session.target" ];
        };
      };
    };
  };
}
