---
# ubuntu 16.04

- name: Install unity tweak tool
  apt: pkg=unity-tweak-tool state=latest
  tags: ubuntu

# - name: Install gnome tweak tool
#   apt: pkg=gnome-tweak-tool state=latest
#   tags: ubuntu

- name: Remove unused apps
  apt: pkg={{item}} state=absent
  with_items:
    - rhythmbox
    - thunderbird
  tags: ubuntu
# - name: Create greeter override
#   copy:
#     src: gschema.override
#     dest: /usr/share/glib-2.0/schemas/10_unity_greeter_background.gschema.override
#   notify: Compile glib schemas
#   tags: ubuntu
