---

- name: Create install dir
  file:
    path: "/opt/iris"
    state: directory
    owner: root
    group: root
  tags: iris

- name: Unzip tar
  unarchive:
    src: "Iris-0.7.7-Linux-64bit.tar.gz"
    dest: "/opt/iris"
    remote_src: no
  tags: iris

- name: Create symlink to desktop file
  file:
    src: "/opt/iris/Iris.desktop"
    dest: "/usr/share/applications/iris.desktop"
    state: link
  tags: iris

- name: Copy autostart entry
  copy:
    src: iris.autostart.desktop
    dest: "/home/{{ username }}/.config/autostart/iris.desktop"
    owner: "{{ username }}"
    group: "{{ username }}"
  tags: iris
