---
# common

- name: Install common packages
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - curl
    - vim
    - ack-grep
    - xclip
    - trash-cli
    - ufw
    - dnsutils
    - tree
    # - ppa-purge
    - sshfs
    - htop
    - libnss3-tools
    - libnotify-bin
    - notify-osd
    - net-tools
    - tldr
  tags: common

#- name: Create symlink to ack
#  file: src=/usr/bin/ack-grep dest=/usr/bin/ack owner=root group=root state=link
#  tags: common

- name: Create downloads directory
  file:
    path: /srv/downloads
    owner: root
    group: root
    state: directory
  tags: common

#- name: Copy trim cron task
#  copy: src=etc/cron.daily/trim dest=/etc/cron.daily/trim owner=root group=root mode=0755
#  tags: common

# - include_tasks: python3.yml
#   # when: "computer_type == 'nas'"
#   tags:
#     - common
#     - python

# - name: Upgrade pip
#   command: pip install --upgrade pip
#   tags: common

# - name: Install docker-py
#   pip:
#     name: docker-py
#     state: present
#   tags: common

#- name: Install cheat
#  pip: name=cheat state=present
#  tags: common

# - name: Display all variables/facts known for a host
#   debug: var=hostvars[inventory_hostname]
#   tags: facts

- name: Create the full-upgrade script
  copy:
    src: full-upgrade
    dest: /usr/local/bin/full-upgrade
    owner: root
    group: root
    mode: 0755
  tags: common
