---
# install yarn

- name: Add an Apt signing key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present
  tags: yarn

- name: Add repo
  apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    state: present
  tags: yarn

- name: Install yarn
  package:
    name: yarn
    install_recommends: no
    state: latest
  tags: yarn
