FROM caddy:2.7-builder AS builder

RUN xcaddy build \
    --with github.com/hairyhenderson/dns.providers.cloudflare

FROM caddy:2.7

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

COPY Caddyfile /etc/caddy/Caddyfile
COPY site /srv
