#!/usr/bin/env bash
set -euo pipefail

# ensure it's run as root
if [ "$EUID" -ne 0 ]; then
	echo "Please run as root"
	exit 1
fi

mount /dev/disk/by-label/nixos /mnt
# UEFI systems
mkdir -p /mnt/boot
mount -o umask=077 /dev/disk/by-label/boot /mnt/boot

ls /mnt/boot
