#!/usr/bin/env bash
set -euo pipefail

# ensure it's run as root
if [ "$EUID" -ne 0 ]; then
	echo "Please run as root"
	exit 1
fi

# Safely unmount everything under /mnt if it exists
if mountpoint -q /mnt; then
  umount -R /mnt
fi

disk_type="${1:-ext4}"

if [ "$disk_type" = "ext4" ]; then
  mount /dev/disk/by-label/nixos /mnt
  # UEFI systems
  mkdir -p /mnt/boot
  mount -o umask=077 /dev/disk/by-label/boot /mnt/boot
elif [ "$disk_type" = "btrfs" ]; then
  # mount root subvolume
  mount -o subvol=@ /dev/disk/by-partlabel/root-main-disk /mnt

  # Create directories just in case the subvol is empty
  mkdir -p /mnt/{home,nix,var/log}

  # mount subvolumes
  mount -o subvol=@home /dev/disk/by-partlabel/root-main-disk /mnt/home
  mount -o subvol=@nix /dev/disk/by-partlabel/root-main-disk /mnt/nix
  mount -o subvol=@log /dev/disk/by-partlabel/root-main-disk /mnt/var/log

  # UEFI systems
  mkdir -p /mnt/boot
  mount -o umask=077 /dev/disk/by-partlabel/boot /mnt/boot

  echo "Btrfs subvolumes on /mnt:"
  btrfs subvolume list /mnt
else
  echo "Invalid disk type: $disk_type"
  exit 1
fi

echo "----------- /mnt"
ls -alh /mnt

echo "----------- /mnt/boot"
ls -alh /mnt/boot

echo "----------- /mnt/home"
ls -alh /mnt/home

echo "----------- /mnt/nix"
ls -alh /mnt/nix

echo "----------- /mnt/var/log"
ls -alh /mnt/var/log
