---

# - name: Add Apt signing key
#   apt_key: id=EA312927 keyserver=hkp://keyserver.ubuntu.com:80 state=present

- name: Add program
  apt_repository: repo='ppa:stefansundin/powermate' state=present
  tags: powermate

- name: Install powermate
  apt: pkg=powermate state=latest
  tags: powermate
