{
  imports = [
    ./blocky
    ./caddy
    ./coredns
    ./ntfy
    ./btrbk.nix
    ./forgejo.nix
    ./forgejo-backup.nix
    ./immich.nix
    ./jellyfin.nix
    ./mount-vault.nix
    ./notify.nix
    ./pocketid.nix
    ./pocketid-backup.nix
    ./sshd.nix
    ./wireguard.nix
  ];
}
