---

- name: Copy channels file
  copy:
    src: channels-dvr
    dest: /etc/ufw/applications.d/channels-dvr
  tags: ufw

- name: allow Channels DVR
  ufw:
    name: ChannelsDVR
    from_ip: "{{ subnet_cidr }}"
    rule: allow
  tags: ufw