---
#

- name: Copy emby file
  copy:
    src: emby-server
    dest: /etc/ufw/applications.d/emby-server
  tags: ufw

- name: Allow Emby server
  ufw:
    name: EmbyServer
    from_ip: "{{ subnet_cidr }}"
    rule: allow
  tags: ufw
