---
- name: allow ssh
  ufw:
    name: OpenSSH
    from_ip: "{{ subnet_cidr }}"
    rule: allow

# - import_tasks: channels-dvr.yml
# - import_tasks: emby-server.yml
# - import_tasks: plex-server.yml
- import_tasks: unifi-network-app.yml
# - import_tasks: pihole.yml
- import_tasks: caddy.yml

# - name: plex external
#   ufw:
#     to_port: "32400"
#     rule: allow

