---
# ufw-workstation

- name: allow ssh
  ufw:
    to_port: "22"
    rule: allow
  tags: ufw

- name: allow web dev
  ufw:
    to_port: "3000"
    rule: allow
  tags: ufw

# - name: allow http access from local network
#   command: ufw allow from any to any port 80
#   tags: ufw

# - name: allow syncthing
#   ufw:
#     name: syncthing
#     rule: allow
#   tags: ufw

# - name: allow hdhomerun discovery
#   ufw:
#     from_ip: "{{ subnet_cidr }}"
#     proto: "udp"
#     to_port: 65001
#     rule: allow
#   tags: ufw

# - name: allow client services for hdhomerun record
#   ufw:
#     from_ip: "{{ subnet_cidr }}"
#     proto: "tcp"
#     to_port: 62500
#     rule: allow
#   tags: ufw
