---

- name: Copy unifi file
  copy:
    src: unifi-network-app
    dest: /etc/ufw/applications.d/unifi-network-app
  tags: ufw

- name: allow unifi server
  ufw:
    name: UnifiNetworkApp
    from_ip: "{{ subnet_cidr }}"
    rule: allow
  tags: ufw
