---
# ssh server

- name: Install openssh-server
  apt:
    pkg: openssh-server
    state: latest
  tags: sshd

- name: Copy sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0640
  notify: Restart sshd
  tags: sshd
  when: ansible_distribution == 'Ubuntu'

- name: Copy sshd_config
  template:
    src: sshd_config_debian12.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0640
  notify: Restart sshd
  tags: sshd
  when: ansible_distribution == 'Debian'