#!/usr/bin/env bash

# Backup ssh keys and other private stuff
USERNAME=$(id -u -n)
USERNAME=${USERNAME:-unknown}

HOSTNAME=$(hostname -s)
HOSTNAME=${HOSTNAME:-unknown}

DEVICE_PATH=/media/$USERNAME/Backup
RSYNC_OPTS='-az --delete-after --progress'

if [ -f /etc/NIXOS ]; then
  DEVICE_PATH=/run$DEVICE_PATH
fi

if [ -d "$DEVICE_PATH" ]; then
  BACKUP_DIR=$DEVICE_PATH/backup/$USERNAME/$HOSTNAME

  mkdir -p $BACKUP_DIR
  mkdir -p /home/$USERNAME/secret/ssh-backup/$HOSTNAME

  # sync the ssh directory to the secret directory
  rsync $RSYNC_OPTS /home/$USERNAME/.ssh /home/$USERNAME/secret/ssh-backup/$HOSTNAME

  # sync the secret-cipher directory to the backup location
  rsync $RSYNC_OPTS /srv/ext/$USERNAME/secret-cipher $BACKUP_DIR

  # tar -czf $BACKUP_DIR/secrets.tgz -C /home/$USERNAME .ssh secret

  # BOOTSTRAP_FILE=/home/$USERNAME/sysconf/nix/machines/$HOSTNAME/bootstrap.sh
  # if [ -f "$BOOTSTRAP_FILE" ]; then
  #   rsync $RSYNC_OPTS $BOOTSTRAP_FILE $BACKUP_DIR
  # fi

  echo "Backup secrets" "Finished processing"
else
  echo "Backup secrets" "Device not attached. Nothing was done."
fi

exit 0
