#!/usr/bin/env bash
# use `umount /path/to/mount` to unmount
# NOTE: umount *not* unmount

if [ ! -d "$2" ]; then
  sudo mkdir -p "$2"
  sudo chown nelly:users "$2"
fi

sshfs -o IdentityFile=~/.ssh/id_ed25519 "illmatic:$1" "$2"
