---
# cryptomator cli

- name: Create cryptomator-cli dir in downloads
  ansible.builtin.file:
    path: "{{ downloads_path }}/cryptomator-cli"
    state: directory
  tags: cryptomator-cli

- name: Download the Cryptomator zip
  ansible.builtin.get_url:
    url: https://github.com/cryptomator/cli/releases/download/{{ cryptomator_version }}/cryptomator-cli-{{ cryptomator_version }}-linux-x64.zip
    dest: "{{ downloads_path }}/cryptomator-cli.zip"
  tags: cryptomator-cli

- name: Extract cryptomator-cli.zip into /opt/cryptomator-cli
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ downloads_path }}/cryptomator-cli.zip"
    dest: "{{ downloads_path }}/cryptomator-cli"
  tags: cryptomator-cli

- name: Copy the files to /opt.
  ansible.builtin.command:
    cmd: "cp -r {{ downloads_path }}/cryptomator-cli/target/cryptomator-cli /opt"
    creates: /opt/cryptomator-cli
  tags: cryptomator-cli
