---
# install wkhtmltopdf

- name: Download tgz
  get_url:
    url: "https://downloads.wkhtmltopdf.org/0.12/{{wkhtmltopdf_version}}/wkhtmltox-{{wkhtmltopdf_version}}_linux-generic-amd64.tar.xz"
    dest: "{{downloads_path}}/wkhtmltox-{{wkhtmltopdf_version}}_linux-generic-amd64.tar.xz"
  tags:
    - wkhtmltopdf
    - wkhtml

- name: Unpack tgz file
  unarchive:
    src: "{{downloads_path}}/wkhtmltox-{{wkhtmltopdf_version}}_linux-generic-amd64.tar.xz"
    dest: "/opt/"
    copy: no
  tags:
    - wkhtmltopdf
    - wkhtml
