# install node in node_user's home directory
# https://www.digitalocean.com/community/articles/how-to-install-an-upstream-version-of-node-js-on-ubuntu-12-04
# https://gist.github.com/isaacs/579814
# export PATH=$HOME/local/bin:$PATH

- name: Install build-essential
  apt: pkg=build-essential state=latest
  tags: node

- name: Create local directory
  file: path=/home/{{ node_user }}/local state=directory owner={{ node_user }} group={{ node_user }}
  tags: node

- name: Create node install directory
  file: path=/home/{{ node_user }}/node-latest-install state=directory owner={{ node_user }} group={{ node_user }}
  tags: node

- name: Download node binaries
  get_url: url=http://nodejs.org/dist/node-latest.tar.gz dest=/home/{{ node_user }}/node-latest-install/node-latest.tar.gz
  sudo: no
  tags: node

- name: Extract tar
  command: tar xzf /home/{{ node_user }}/node-latest-install/node-latest.tar.gz --strip-components=1 chdir=/home/{{ node_user }}/node-latest-install creates=/home/{{ node_user }}/node-latest-install/Makefile
  sudo: no
  tags: node

- name: Run configure
  command: ./configure --prefix=/home/{{ node_user }}/local chdir=/home/{{ node_user }}/node-latest-install creates=/home/{{ node_user }}/node-latest-install/config.mk
  sudo: no
  tags: node

- name: Run make
  command: make install chdir=/home/{{ node_user }}/node-latest-install creates=/home/{{ node_user }}/local/bin/node
  sudo: no
  tags: node
