---
# backup server
# TODO: Unattended upgrades

- hosts: backup
  become: yes
  become_method: sudo
  vars_files:
    - vaults/backup.yml
  vars:
    username: nelly
    computer_type: backup
  roles:
    - common
    - common-server
    - backup-server
    - nix
    - sshd
    - ufw
