---
# Laptop

- hosts: laptop
  become: yes
  become_method: sudo
  vars:
    username: nelly
    computer_type: laptop
    subnet_cidr: "192.168.1.0/24"
  roles:
    - common
    - common-desktop
    - docker
    - ufw
    - iris
    - mongo
    - enpass
    - google-cloud
