---
# Workstation
# ansible-galaxy install -r requirements.yml

- hosts: workstation
  become: yes
  become_method: sudo
  vars:
    username: nelly
    computer_type: workstation
    subnet_cidr: "192.168.1.0/24"
    appimage_download_urls:
      # - name: logsec
      #   url: https://github.com/logseq/logseq/releases/download/0.10.5/Logseq-linux-x64-0.10.5.AppImage
      #   state: present
      # - name: filen
      #   url: https://cdn.filen.io/desktop/release/filen_x86_64.AppImage
      #   state: present
      # - name: obsidian
      #   url: https://github.com/obsidianmd/obsidian-releases/releases/download/v1.5.3/Obsidian-1.5.3.AppImage
      #   state: present
  roles:
    # - common
    # - common-desktop
    # - hosts
    #- git
    #- java-jdk
    # - docker
    # - docker-compose - comes installed with docker now
    #- franklinkim.docker
    # - multimedia # music ripping mostly
    #- sublime3
    #- vagrant
    - ufw
    # - mongo
    #- princexml
    #- packer
    # - go
    #- hugo
    #- nvm
    #- iris
    # - google-cloud
    #- qtfaststart
    #- wkhtmltopdf
    # - sbt
    # - signal
    # - syncthing
    # - enpass
    #- sshd
    #- clementine
    #- plex
    # - { role: ocha.yarn, tags: yarn }
    # - terraform
    #- terraform-provider-ansible
    #- yarn
    #- virtualbox
    # - task
    - role: spreadcat.appimage
      tags: appimage
    - role: gnome-desktop-entries
      tags: desktop-entries
