host = "ruca"
user = "nelly"
editor = "codium --new-window --wait"
stow_packages = ["common", "code", "wezterm"]
backup_dirs = ["Audio", "Documents", "Notes", "Pictures", "code", "secret-cipher", "sysconf"]
