---
- name: Create user to run caddy as
  user:
    name: caddy
    shell: /bin/false
  register: caddy_user
  tags: caddy

- name: Print the uid:gid of caddy user
  ansible.builtin.debug:
    msg: "user:group {{ caddy_user.uid }}:{{ caddy_user.group }}"
  when: caddy_user is defined
  tags: caddy

- name: Create /srv/docker/caddy directory
  file:
    path: /srv/docker/caddy
    state: directory
    owner: caddy
    group: caddy
  tags: caddy

- name: Generate caddy docker compose file
  template:
    src: caddy-compose.yml.j2
    dest: /srv/docker/caddy/compose.yml
    owner: caddy
    group: caddy
  tags: caddy

- name: Copy caddy binary
  copy:
    src: caddy_linux_amd64_custom
    dest: /srv/docker/caddy/caddy_linux_amd64_custom
    owner: caddy
    group: caddy
  tags: caddy

- name: Copy Dockerfile file
  copy:
    src: caddy-Dockerfile
    dest: /srv/docker/caddy/Dockerfile
    owner: caddy
    group: caddy
  tags: caddy

- name: Generate Caddyfile
  template:
    src: Caddyfile.j2
    dest: /srv/docker/caddy/Caddyfile
    owner: caddy
    group: caddy
  tags: caddy

- name: Create /srv/docker/caddy/site directory
  file:
    path: /srv/docker/caddy/site
    state: directory
    owner: caddy
    group: caddy
  tags: caddy

- name: Copy index.html file
  copy:
    src: index.html
    dest: /srv/docker/caddy/site/index.html
    owner: caddy
    group: caddy
  tags: caddy
