---

- name: Create user to run channels as
  user:
    name: channels
    shell: /bin/false
  register: channels_user
  tags: channels

- name: Print the uid:gid of channels user
  ansible.builtin.debug:
    msg: "user:group {{ channels_user.uid }}:{{ channels_user.group }}"
  when: channels_user is defined
  tags: channels

- name: Create /srv/docker/channels directory
  file:
    path: /srv/docker/channels
    state: directory
    owner: channels
    group: channels
  tags: channels

- name: Copy channels docker compose file
  template:
    src: channels-compose.yml.j2
    dest: /srv/docker/channels/compose.yml
    owner: channels
    group: channels
  tags: channels

- name: Create config dir
  file:
    path: /mnt/dvr-config
    state: directory
    owner: channels
    group: channels
  tags: channels

- name: Create recordings dir
  file:
    path: /mnt/dvr-recordings
    state: directory
    owner: channels
    group: channels
  tags: channels
