---
- name: Create /srv/docker/homepage directory
  file:
    path: /srv/docker/homepage
    state: directory
    owner: root
    group: root

- name: Generate homepage docker compose file
  template:
    src: homepage-compose.yml.j2
    dest: /srv/docker/homepage/compose.yml
    owner: root
    group: root

- name: Create /srv/docker/homepage/config directory
  file:
    path: /srv/docker/homepage/config
    state: directory
    owner: root
    group: root

- name: Copy homepage files
  copy:
    src: "{{item}}"
    dest: /srv/docker/homepage/config
    owner: root
    group: root
    mode: 0644
  loop:
    - homepage/bookmarks.yaml
    - homepage/docker.yaml
    - homepage/services.yaml
    - homepage/settings.yaml
    - homepage/widgets.yaml
