---

- name: Create user to run plex as
  user:
    name: plex
    shell: /bin/false
  register: plex_user
  tags: plex

- name: Print the uid:gid of plex user
  ansible.builtin.debug:
    msg: "user:group {{ plex_user.uid }}:{{ plex_user.group }}"
  when: plex_user is defined
  tags: plex

- name: Create /srv/docker/plex directory
  file:
    path: /srv/docker/plex
    state: directory
    owner: plex
    group: plex
  tags: plex

- name: Copy plex docker compose file
  template:
    src: plex-compose.yml.j2
    dest: /srv/docker/plex/compose.yml
    owner: plex
    group: plex
  tags: plex

- name: Create config dir
  file:
    path: /mnt/plex
    state: directory
    owner: plex
    group: plex
  tags: plex
