---
# sublime text 3

# - name: Download .deb file
#   get_url:
#     url: "https://download.sublimetext.com/sublime-text_build-{{ sublime_build }}_amd64.deb"
#     dest: "{{ downloads_path }}/sublime-text_build-{{ sublime_build }}_amd64.deb"
#   tags: sublime3

# - name: Install sublime text 3
#   apt:
#     deb: "{{ downloads_path }}/sublime-text_build-{{ sublime_build }}_amd64.deb"
#     state: installed
#   tags: sublime3

- name: Add repo key
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present
  tags: sublime3

- name: Add repo
  apt_repository:
    repo: 'deb https://download.sublimetext.com/ apt/stable/'
    state: present
  tags: sublime3

- name: Install mongodb shell
  apt: pkg=sublime-text state=latest
  tags: sublime3
