---

- name: Download .deb
  get_url:
    url: "https://www.princexml.com/download/prince_{{princexml_version}}_ubuntu{{ ansible_distribution_version }}_amd64.deb"
    dest: "{{downloads_path}}/prince_{{princexml_version}}.deb"

- name: Install deb
  apt:
    deb: "{{downloads_path}}/prince_{{princexml_version}}.deb"
